// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TexttoColor
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("hex")]
        public string Hex { get; set; }

        [JsonProperty("rgb")]
        public string Rgb { get; set; }

        [JsonProperty("hsl")]
        public string Hsl { get; set; }

        [JsonProperty("cmyk")]
        public string Cmyk { get; set; }

        [JsonProperty("ansi16")]
        public long Ansi16 { get; set; }

        [JsonProperty("channels")]
        public Channels Channels { get; set; }
    }

    public partial class Channels
    {
        [JsonProperty("rgbChannels")]
        public long RgbChannels { get; set; }

        [JsonProperty("cmykChannels")]
        public long CmykChannels { get; set; }

        [JsonProperty("ansiChannels")]
        public long AnsiChannels { get; set; }

        [JsonProperty("hexChannels")]
        public long HexChannels { get; set; }

        [JsonProperty("hslChannels")]
        public long HslChannels { get; set; }
    }
}
